global:
  scrape_interval: 5s

scrape_configs:
  - job_name: test
    static_configs:
      - targets:
        - exporter:9091
  - job_name: cb7
    basic_auth:
      username: Administrator
      password: password
    static_configs:
      - targets:
        - cb7:8091
