name: Build static binaries

on:
  push:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go Faster
      uses: WillAbides/setup-go-faster@v1.6.0
      with:
        go-version: 1.17.x
    
    - name: Build binary
      run: |
        mkdir build
        $GOROOT/bin/go build -o ./build/cmos-exporter-$(git rev-parse --short HEAD)-${{ matrix.os }}-amd64 -tags osusergo,netgo ./cmd/cmos-exporter
      shell: bash
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: cmos-exporter-${{ matrix.os }}-amd64
        path: build/*
