name: Build static binaries

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: [amd64]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go Faster
      uses: WillAbides/setup-go-faster@v1.6.0
      with:
        go-version: 1.17.x
    
    - name: Build binary
      run: |
        CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./yacpe-build -tags osusergo,netgo ./cmd/yacpe
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: yacpe-${{ matrix.goos }}-${{ matrix.goarch }}
        path: yacpe-build
