name: Build and push Docker image

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/markspolakovs/yacpe:${{ github.sha }}
    - name: Push the Docker image
      run: docker push ghcr.io/markspolakovs/yacpe:${{ github.sha }}
